Testing 7 - again with composer install

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,6 +7,23 @@ jobs:
 
     working_directory: ~/repo
 
+    install_composer: &install_composer
+      command: |
+        cd /tmp
+        EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
+        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+        ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+        then
+            >&2 echo 'ERROR: Invalid installer signature'
+            rm composer-setup.php
+            exit 1
+        fi
+        sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+        RESULT=$?
+        rm composer-setup.php
+        exit $RESULT
+
     steps:
       - checkout
 
@@ -17,7 +34,7 @@ jobs:
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-
 
-      - run: composer install -n --prefer-dist
+      - run: composer install -n --prefer-source
 
       - save_cache:
           paths:
